# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.100:3306/yunshu?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: Szw371517577@
  jackson:
    parser:
      allow-backslash-escaping-any-character: true
  thymeleaf:
    cache: false
    mode: HTML5
# Logger Config
logging:
  level:
    top.zyaire.videogether: debug

mybatis:
  type-aliases-package: top.zyaire.videogether.domain
  mapper-locations: classpath:generator/*.xml
server:
  port: 8090


zuul:
  routes:
    client-a:
      path: /api/**
      url: http://localhost:10008 #client-a的地址
